// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltwpkknprsngrbcbmzou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0d3Bra25wcnNuZ3JiY2Jtem91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NjYzMjYsImV4cCI6MjA3MjE0MjMyNn0.daUZQvjgp3hHDhn9gKFH0e8qtJOdU-rdWyBC5wXnEE8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});